/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hadik;

import java.util.ArrayList;
import javax.swing.SwingConstants;

/**
 *
 * @author MSI
 */
public class HighScoreMenu extends javax.swing.JFrame {

    /**
     * Creates new form HighScoreMenu
     */
    public HighScoreMenu() {
        initComponents();
        HighScore HS = new HighScore();
        ArrayList<String> skore = HS.getScore();
        if (!skore.isEmpty()) prvý.setText(skore.get(0));
        if (skore.size() > 1) druhý.setText(skore.get(1));
        if (skore.size() > 2) tretí.setText(skore.get(2));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        prvý = new javax.swing.JLabel("", SwingConstants.CENTER);
        druhý = new javax.swing.JLabel("", SwingConstants.CENTER);
        tretí = new javax.swing.JLabel("", SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("HIGH SCORE:");

        prvý.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        prvý.setForeground(new java.awt.Color(255, 255, 0));
        prvý.setText("Chose:7");
        prvý.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        druhý.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        druhý.setForeground(new java.awt.Color(102, 102, 102));
        druhý.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tretí.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        tretí.setForeground(new java.awt.Color(204, 51, 0));
        tretí.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
            .addComponent(prvý, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(druhý, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tretí, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(prvý, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(druhý, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tretí, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel druhý;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel prvý;
    private javax.swing.JLabel tretí;
    // End of variables declaration//GEN-END:variables
}
